const DEFAULT_CELL_SIZE_IN_METERS = 500;
const DEFAULT_ZOOM = 12;
const DEFAULT_LOCATIONS_SIZE = 200;

const ONE_GEO_DEGREE_TO_METERS = 111000;

const X = 0;
const Y = 1;

const SQUARE_MAP = 0;
const HEX_MAP = 1;

const H3_RESOLUTION = 9;
const H3_RADIUS = 32;
